
language: csharp
solution: Wax.sln

install:
  - nuget restore Wax.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Wax.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./WaxTest/bin/WaxTest.dll

