
language: csharp
solution: Wax.sln

before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Wax.sln
after_script:
  - nunit-console /release/test/WaxTest/UnitTest1.dll
  

