build:
  project: Wax.sln
environment:
  COVERALLS_REPO_TOKEN:
    secure: M0GwzuAXUwVXsjPnWbQ7hgrYRBed0OJvccMStfqXhBCbi3ycr67mXv1c6+jdv7yL
before_build:
  - nuget restore
after_test:
  - cmd: .\after_test.cmd
