build:
  project: Wax.sln
environment:
  COVERALLS_REPO_TOKEN:
    secure: QXbLYR/Kj5kKbC1VfgWrownBEhUzuXYiTpNpx1hXsvAx8yYVZEYPqocUCtJFx0Ye
before_build:
  - nuget restore
after_test:
  - cmd: .\after_test.cmd